### ISSUE TITLE
What is the training/testing datasets?

### ISSUE THREAD

**Issue by TianweiXing** [philipperemy/very-deep-convnets-raw-waveforms#2]
Hi,
I'm pretty interested in this project, and trying to run it myself.
However I noticed that in the "model_data.py", the DataReader is reading non-existing files.

```
class DataReader:
    def __init__(self):
        self.train_files = glob(os.path.join(OUTPUT_DIR_TRAIN, '**.pkl'))
        print('training files =', len(self.train_files))
        self.test_files = glob(os.path.join(OUTPUT_DIR_TEST, '**.pkl'))
print('testing files =', len(self.test_files))
```
But what I get for ESC-50 in raw .wav file. 

I'm wondering where can I get these training files?

Thanks!

**Comment by durkadurk** [comment]
The .pkl files will be created by running 'process_data.py'. Before you do so, edit the paths in 'constants.py'. The sounds used (as described in the paper) are coming from the UrbanSound8k dataset.

**Comment by philipperemy** [comment]
You can download the dataset here: http://urbansounddataset.weebly.com/urbansound8k.html

@durkadurk thanks for the guidance :)
